In [2]:
import pandas as pd

In [ ]:
recebido = { 
  "Gestão Estratégica" : { 
    "GE01" : 
      { "O planejamento está documentado ?": "Não",
        "Existe revisão periódica ?": "Existe de forma incorreta",
        "Os gestores conhecem o planejamento ?": "Sim",
        "As metas derivam do planejamento ?": "Não"
      },
    "GE02" : 
      { "As metas são numéricas ?" : "Sim",
        "As metas possuem prazo ?" : "Não possuem",
        "Existe responsável por cada meta ?": "Sim",
        "As metas são acompanhadas ?" : "Parcialmente"
      }
  },
  "Financeiro" : { 
    "F01" : 
      { "O fluxo é atualizado diariamente?" : "Sim",
        "O fluxo contempla todas as entradas?" : "Não contempla",
        "O fluxo contempla todas as saídas?" : 'Não',
        "Existe responsável pela atualização?" : "De forma incorreta"
      },
    "F02" : 
      { "O fluxo é analisado periodicamente?" : "Sim",
        "Decisões de compra utilizam o fluxo?" : "Não",
        "Decisões de investimento utilizam o fluxo?" : "Sim",
        "Existe reunião de análise financeira?" : "Parcialmente"
      }
  },
}

In [32]:
import json

final = json.dumps(recebido, indent=4, ensure_ascii=False)

In [1]:
estrutura_final = { 
    "Gestão Estratégica" : 
        [
            {"Bloco" : "GE01", "Pergunta" : "Existem reuniões de acompanhamento?", "Resposta" : "Parcialmente"}
        ]
}

In [ ]:
estrutura_final = {}

for pilar, data in recebido.items() :
    estrutura_final[pilar] = []

    for bloco, dados in data.items():
        
        for pergunta, resposta in dados.items() :
            estrutura_final[pilar].append({"Bloco" : bloco, "Pergunta" : pergunta, "Resposta" : resposta})

In [30]:
for pilar, dados in estrutura_final.items() :
        df = pd.DataFrame(dados)

  Bloco                                    Pergunta            Resposta
0   F01           O fluxo é atualizado diariamente?                 Sim
1   F01        O fluxo contempla todas as entradas?       Não contempla
2   F01          O fluxo contempla todas as saídas?                 Não
3   F01        Existe responsável pela atualização?  De forma incorreta
4   F02         O fluxo é analisado periodicamente?                 Sim
5   F02        Decisões de compra utilizam o fluxo?                 Não
6   F02  Decisões de investimento utilizam o fluxo?                 Sim
7   F02       Existe reunião de análise financeira?        Parcialmente

In [ ]:
from io import BytesIO

buffer = BytesIO()

with pd.ExcelWriter(buffer, engine='openpyxl') as writer :
    for pilar, dados in estrutura_final.items() :
        df = pd.DataFrame(dados)
        df.to_excel(writer, sheet_name=pilar, index=False )

buffer.seek(0)

,Gestão Estratégica,Financeiro
0,"{'Bloco': 'GE01', 'Pergunta': 'O planejamento ...","{'Bloco': 'F01', 'Pergunta': 'O fluxo é atuali..."
1,"{'Bloco': 'GE01', 'Pergunta': 'Existe revisão ...","{'Bloco': 'F01', 'Pergunta': 'O fluxo contempl..."
2,"{'Bloco': 'GE01', 'Pergunta': 'Os gestores con...","{'Bloco': 'F01', 'Pergunta': 'O fluxo contempl..."
3,"{'Bloco': 'GE01', 'Pergunta': 'As metas deriva...","{'Bloco': 'F01', 'Pergunta': 'Existe responsáv..."
4,"{'Bloco': 'GE02', 'Pergunta': 'As metas são nu...","{'Bloco': 'F02', 'Pergunta': 'O fluxo é analis..."
5,"{'Bloco': 'GE02', 'Pergunta': 'As metas possue...","{'Bloco': 'F02', 'Pergunta': 'Decisões de comp..."
6,"{'Bloco': 'GE02', 'Pergunta': 'Existe responsá...","{'Bloco': 'F02', 'Pergunta': 'Decisões de inve..."
7,"{'Bloco': 'GE02', 'Pergunta': 'As metas são ac...","{'Bloco': 'F02', 'Pergunta': 'Existe reunião d..."